### ISSUE TITLE
Trying to get started with your Map framework

### ISSUE THREAD

**Issue by profK** [kcudnik/bridgegooglemaps#1]
And I am stumped on how I set my API key?

A HelloWorld level example in your README would be very useful.

**Comment by kcudnik** [comment]
Hey, this framework is ment to be used with Bridge.net core libraries to compile/work
and as for API key, you still need to manually add as include in *html/*php file like this:

```html
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=API_KEY"></script>
```

also i would recommend to use https://retyped.com/?q=google%20maps#search since this is automatically generated library from defenetly typed repo and its more accurate.
I started this repo before bridge team created retyped.net frameworks.
And from this point i probably wont be making any updates any more since it would be waist of my time. Thanks for stepping by!
